export const users = [
  {
    uid: '',
    email: 'user@example.com',
    displayName: 'HITPanda',
    address: 'Ngõ 66 Hồ Tùng Mậu, Mai Dịch, Cầu Giấy, Hà Nội',
    accessToken: '',
    photoURL: '',
    phoneNumber: '0328462112',
    providerId: 'password',
    roles: 'customer',
    createdAt: null,
    updatedAt: null,
  },
];

export const products = [
  {
    productId: '1',
    name: 'Burger bò nướng khoai tây lát',
    photoURL:
      'https://product.hstatic.net/200000291375/product/item_01_e8d6cc3ee923425690ccaa95467a3cac_master.jpg',
    price: 48000,
    description: [
      'Một bữa ăn đầy đủ chất dinh dưỡng cho bạn sức khỏe tốt, sự dẻo dai, và thân hình đúng chuẩn. Trong xã hội hiện đại, mọi thứ được tối giản đáng kể, và các món ăn cũng vậy. Bạn không phải mất công chuẩn bị nhiều món để tương xứng với số lượng dưỡng chất nạp vào cơ thể, mà nay trong một chiếc burger cũng giúp bạn thực hiện dễ dàng điều này.',
      'Vậy nguyên liệu chính làm nên chiếc bánh nhỏ xinh này bao gồm những gì? Đó là tôm tươi, thịt gà sạch, xúc xích và một chút phô mai béo ngậy, thơm ngọt. Ngoài ra, khi thực hiện món ăn này tại nhà hoặc đặt hàng từ các quán burger thì bạn cũng có thể thêm một ít rau sống, vừa giúp bổ sung chất xơ, vừa tạo sự hài hòa, thanh mát cho tổng thể món ăn.',
      'Bạn là tín đồ của thịt bò ? Bạn muốn biến tấu những miếng thịt bò thành một món ăn khác? Đừng lo, hãy đến với chúng tôi, bạn sẽ được thưởng thức những suất hamburger bò đặc biệt tại cửa hàng này.',
    ],
    category: 'Burger',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '2',
    name: 'Hamburger Trứng, Thịt Bò & Xúc Xích',
    photoURL:
      'https://product.hstatic.net/200000291375/product/item_02_85dd97939aef4ea0a1184b987715b84e_master.jpg',
    price: 60000,
    description: [
      'Món ăn này vừa gọn nhẹ, thuận tiện, nhanh no, dễ ăn và phù hợp với khẩu vị của nhiều người. Nếu bạn cần dinh dưỡng thì hãy nghĩ ngay đến chiếc bánh này cho khẩu phần ăn nhé!',
      'Dai dai của phô mai hòa quyện cùng với trứng gà và miếng thịt bò chắc chắn sẽ làm bạn khó cưỡng lại khi cầm chiếc bánh này trong tay đó.',
      'Cũng là vị dai dai của phô mai nhưng vị khán hẳn chiếc bánh hamburger trên bởi thay vị trứng là vị thơm của gà. Hầu như mọi chuỗi đồ ăn nhanh đều có món bánh hamburger với lớp vỏ mềm mịn, thịt thơm phức, phô mai béo ngậy và nước sốt ngon tuyệt.',
      'Một chiếc bánh hamburger cung cấp cho bạn đầy đủ dinh dưỡng gồm chất xơ, protein, tinh bột, chất béo, từ đó bạn có năng lượng và năng lượng cho cả ngày.',
    ],
    category: 'Burger',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '3',
    name: 'Burger vòng hành chiên (size vừa)',
    photoURL:
      'https://product.hstatic.net/200000291375/product/item_03_28c535c005224abc87386e079f9c56e7_master.jpg',
    price: 60000,
    description: [
      'Một bữa ăn đầy đủ chất dinh dưỡng cho bạn sức khỏe tốt, sự dẻo dai, và thân hình đúng chuẩn. Trong xã hội hiện đại, mọi thứ được tối giản đáng kể, và các món ăn cũng vậy. Bạn không phải mất công chuẩn bị nhiều món để tương xứng với số lượng dưỡng chất nạp vào cơ thể, mà nay trong một chiếc burger cũng giúp bạn thực hiện dễ dàng điều này.',
      'Vậy nguyên liệu chính làm nên chiếc bánh nhỏ xinh này bao gồm những gì? Đó là tôm tươi, thịt gà sạch, xúc xích và một chút phô mai béo ngậy, thơm ngọt. Ngoài ra, khi thực hiện món ăn này tại nhà hoặc đặt hàng từ các quán burger thì bạn cũng có thể thêm một ít rau sống, vừa giúp bổ sung chất xơ, vừa tạo sự hài hòa, thanh mát cho tổng thể món ăn.',
      'Bạn là tín đồ của thịt bò ? Bạn muốn biến tấu những miếng thịt bò thành một món ăn khác? Đừng lo, hãy đến với chúng tôi, bạn sẽ được thưởng thức những suất hamburger bò đặc biệt tại cửa hàng này.',
    ],
    category: 'Burger',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '4',
    name: 'Burger bò nướng whopper',
    photoURL:
      'https://product.hstatic.net/200000291375/product/item_03_28c535c005224abc87386e079f9c56e7_master.jpg',
    price: 55000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Burger',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '5',
    name: 'Burger 2 miếng bò nướng phô mai thịt xông khói whopper',
    photoURL:
      'https://product.hstatic.net/200000291375/product/item_03_28c535c005224abc87386e079f9c56e7_master.jpg',
    price: 145000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Burger',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '6',
    name: 'Shrimp & Olive Pizza',
    photoURL:
      'https://product.hstatic.net/200000291375/product/pizza_01_46536590e6ca48f7896f1a3825216a5d_master.jpg',
    price: 259000,
    description: [
      'Đa dạng hương vị, hình thức đẹp mắt, đầy đủ năng lượng và dinh dưỡng,…đó là những lý do khiến Pizza vô cùng phổ biến và được bình chọn là một trong những món bánh được yêu thích nhất trên thế giới. Cho đến ngày nay người ta vẫn còn tranh cãi về nguồn gốc ra đời của món bánh này. Một số tư liệu cho rằng, bánh Pizza có tiền thân là những chiếc bánh làm bằng bột mì được nướng trên những phiến đá phẳng và nóng xuất hiện lần đầu tiên cũng như trở nên phổ biến tại Napoli – Ý vào khoảng 1000 năm trước. Nhưng một số tài liệu khác lại nói rằng người Roman (La Mã cổ đại) và người Phoenici của xứ Hy Lạp mới là những người đầu tiên đã chế biến thành công Pizza bởi họ vô tình biết được bí mật của công thức nhào bột với nước và nướng bánh trên đá sau đám cháy.',
      'Mặc dù chưa có những khẳng định chắc chắn rằng chiếc bánh Pizza đầu tiên xuất hiện ở đâu, nhưng ngày nay khi nhắc đến Pizza thì ai cũng nghĩ ngay tới Italia – đất nước có hình chiếc giày, bởi lẽ đây chính là đất nước có những nét văn hóa ẩm thực Pizza mà không đâu có thể sánh được.',
    ],
    category: 'Pizza',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '7',
    name: 'Cheese Mania - Pizza Phô Mai hảo hạng',
    photoURL:
      'https://product.hstatic.net/200000291375/product/pizza_01_46536590e6ca48f7896f1a3825216a5d_master.jpg',
    price: 199000,
    description: [
      'Đa dạng hương vị, hình thức đẹp mắt, đầy đủ năng lượng và dinh dưỡng,…đó là những lý do khiến Pizza vô cùng phổ biến và được bình chọn là một trong những món bánh được yêu thích nhất trên thế giới. Cho đến ngày nay người ta vẫn còn tranh cãi về nguồn gốc ra đời của món bánh này. Một số tư liệu cho rằng, bánh Pizza có tiền thân là những chiếc bánh làm bằng bột mì được nướng trên những phiến đá phẳng và nóng xuất hiện lần đầu tiên cũng như trở nên phổ biến tại Napoli – Ý vào khoảng 1000 năm trước. Nhưng một số tài liệu khác lại nói rằng người Roman (La Mã cổ đại) và người Phoenici của xứ Hy Lạp mới là những người đầu tiên đã chế biến thành công Pizza bởi họ vô tình biết được bí mật của công thức nhào bột với nước và nướng bánh trên đá sau đám cháy.',
      'Mặc dù chưa có những khẳng định chắc chắn rằng chiếc bánh Pizza đầu tiên xuất hiện ở đâu, nhưng ngày nay khi nhắc đến Pizza thì ai cũng nghĩ ngay tới Italia – đất nước có hình chiếc giày, bởi lẽ đây chính là đất nước có những nét văn hóa ẩm thực Pizza mà không đâu có thể sánh được.',
    ],
    category: 'Pizza',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '8',
    name: 'Pizza thập cẩm thượng hạng',
    photoURL:
      'https://product.hstatic.net/200000291375/product/pizza_01_46536590e6ca48f7896f1a3825216a5d_master.jpg',
    price: 259000,
    description: [
      'Đa dạng hương vị, hình thức đẹp mắt, đầy đủ năng lượng và dinh dưỡng,…đó là những lý do khiến Pizza vô cùng phổ biến và được bình chọn là một trong những món bánh được yêu thích nhất trên thế giới. Cho đến ngày nay người ta vẫn còn tranh cãi về nguồn gốc ra đời của món bánh này. Một số tư liệu cho rằng, bánh Pizza có tiền thân là những chiếc bánh làm bằng bột mì được nướng trên những phiến đá phẳng và nóng xuất hiện lần đầu tiên cũng như trở nên phổ biến tại Napoli – Ý vào khoảng 1000 năm trước. Nhưng một số tài liệu khác lại nói rằng người Roman (La Mã cổ đại) và người Phoenici của xứ Hy Lạp mới là những người đầu tiên đã chế biến thành công Pizza bởi họ vô tình biết được bí mật của công thức nhào bột với nước và nướng bánh trên đá sau đám cháy.',
      'Mặc dù chưa có những khẳng định chắc chắn rằng chiếc bánh Pizza đầu tiên xuất hiện ở đâu, nhưng ngày nay khi nhắc đến Pizza thì ai cũng nghĩ ngay tới Italia – đất nước có hình chiếc giày, bởi lẽ đây chính là đất nước có những nét văn hóa ẩm thực Pizza mà không đâu có thể sánh được.',
      'Những chiếc bánh Pizza đầu tiên có hình dáng và hương vị như ngày nay ra đời vào năm 1889 để phục vụ nữ hoàng Margherita Teresa Giovanni khi bà đến thăm Napoli. Nguyên liệu chiếc bánh này bao gồm phomai mozzarella, sốt cà chua và lá húng quế tượng trưng cho màu sắc có trên quốc kỳ của đất nước này. Từ đó bánh pizza nhanh chóng được yêu thích và người đầu bếp đầu tiên làm ra nó đã đặt theo tên của nữ hoàng – pizza Margherita.',
    ],
    category: 'Pizza',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '9',
    name: 'Pizza rau củ thập cẩm (Chay)',
    photoURL: '',
    price: 229000,
    description: [
      'Đa dạng hương vị, hình thức đẹp mắt, đầy đủ năng lượng và dinh dưỡng,…đó là những lý do khiến Pizza vô cùng phổ biến và được bình chọn là một trong những món bánh được yêu thích nhất trên thế giới. Cho đến ngày nay người ta vẫn còn tranh cãi về nguồn gốc ra đời của món bánh này. Một số tư liệu cho rằng, bánh Pizza có tiền thân là những chiếc bánh làm bằng bột mì được nướng trên những phiến đá phẳng và nóng xuất hiện lần đầu tiên cũng như trở nên phổ biến tại Napoli – Ý vào khoảng 1000 năm trước. Nhưng một số tài liệu khác lại nói rằng người Roman (La Mã cổ đại) và người Phoenici của xứ Hy Lạp mới là những người đầu tiên đã chế biến thành công Pizza bởi họ vô tình biết được bí mật của công thức nhào bột với nước và nướng bánh trên đá sau đám cháy.',
      'Mặc dù chưa có những khẳng định chắc chắn rằng chiếc bánh Pizza đầu tiên xuất hiện ở đâu, nhưng ngày nay khi nhắc đến Pizza thì ai cũng nghĩ ngay tới Italia – đất nước có hình chiếc giày, bởi lẽ đây chính là đất nước có những nét văn hóa ẩm thực Pizza mà không đâu có thể sánh được.',
      'Những chiếc bánh Pizza đầu tiên có hình dáng và hương vị như ngày nay ra đời vào năm 1889 để phục vụ nữ hoàng Margherita Teresa Giovanni khi bà đến thăm Napoli. Nguyên liệu chiếc bánh này bao gồm phomai mozzarella, sốt cà chua và lá húng quế tượng trưng cho màu sắc có trên quốc kỳ của đất nước này. Từ đó bánh pizza nhanh chóng được yêu thích và người đầu bếp đầu tiên làm ra nó đã đặt theo tên của nữ hoàng – pizza Margherita.',
    ],
    category: 'Pizza',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '10',
    name: 'Pizza Vẹm Xanh thượng hạng',
    photoURL: '',
    price: 299000,
    description: [
      'Đa dạng hương vị, hình thức đẹp mắt, đầy đủ năng lượng và dinh dưỡng,…đó là những lý do khiến Pizza vô cùng phổ biến và được bình chọn là một trong những món bánh được yêu thích nhất trên thế giới. Cho đến ngày nay người ta vẫn còn tranh cãi về nguồn gốc ra đời của món bánh này. Một số tư liệu cho rằng, bánh Pizza có tiền thân là những chiếc bánh làm bằng bột mì được nướng trên những phiến đá phẳng và nóng xuất hiện lần đầu tiên cũng như trở nên phổ biến tại Napoli – Ý vào khoảng 1000 năm trước. Nhưng một số tài liệu khác lại nói rằng người Roman (La Mã cổ đại) và người Phoenici của xứ Hy Lạp mới là những người đầu tiên đã chế biến thành công Pizza bởi họ vô tình biết được bí mật của công thức nhào bột với nước và nướng bánh trên đá sau đám cháy.',
      'Mặc dù chưa có những khẳng định chắc chắn rằng chiếc bánh Pizza đầu tiên xuất hiện ở đâu, nhưng ngày nay khi nhắc đến Pizza thì ai cũng nghĩ ngay tới Italia – đất nước có hình chiếc giày, bởi lẽ đây chính là đất nước có những nét văn hóa ẩm thực Pizza mà không đâu có thể sánh được.',
      'Những chiếc bánh Pizza đầu tiên có hình dáng và hương vị như ngày nay ra đời vào năm 1889 để phục vụ nữ hoàng Margherita Teresa Giovanni khi bà đến thăm Napoli. Nguyên liệu chiếc bánh này bao gồm phomai mozzarella, sốt cà chua và lá húng quế tượng trưng cho màu sắc có trên quốc kỳ của đất nước này. Từ đó bánh pizza nhanh chóng được yêu thích và người đầu bếp đầu tiên làm ra nó đã đặt theo tên của nữ hoàng – pizza Margherita.',
    ],
    category: 'Pizza',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '11',
    name: 'Salad cá hồi cay',
    photoURL: '',
    price: 55000,
    description: [
      'Salad là hỗn hợp gồm có rau củ và nước sốt, có thể được ướp lạnh trước khi dùng hoặc ăn trực tiếp (ở nhiệt độ phòng). Salad là tên gọi tiếng Anh và được xuất hiện lần đầu vào thế kỷ 14 với cách viết là salad hoặc sallet. Ngoài ra, nguồn gốc của tên gọi salad có thể được biến tấu từ cách viết của tiếng Pháp như salade, tiếng Latinh cổ đại là herba Salata và tiếng Latin là salata.',
      'Món salad được xuất hiện từ lâu, dưới nhiều hình thức chế biến khác nhau. Chẳng hạn, người La Mã, người Hy Lạp cổ đại và người Ba Tư đã trộn hỗn hợp rau củ với một loại nước sốt để ăn. Những món ăn rau trộn như vậy đã trở nên phổ biến ở châu Âu sau cuộc xâm lấn của đế chế La Mã và Hy Lạp.',
      'Hầu như nguyên liệu làm nên món salad chủ yếu là các loại rau củ với nước sốt, và tùy theo mục đích sử dụng mới dùng thêm thực phẩm chứa hàm lượng chất đạm như thịt, trứng,… hoặc dùng nước sốt ngọt như kem để thay cho nước sốt giấm quen thuộc.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '12',
    name: 'Salisbury Steak',
    photoURL: '',
    price: 355000,
    description: [
      'Bít tết sẽ là lựa chọn tuyệt vời cho những bữa tiệc sang chảnh tại nhà với hướng vị thơm ngon lại dễ làm. Dưới đây là cách làm bò bít tết tại nhà đơn giản nhất dành cho bạn nào muốn tự tay chuẩn bị bữa tiệc cho gia đình mình dịp lễ này.',
      'Cách làm bò bít tết tại nhà đơn giản, nguyên liệu cần chuẩn bị cũng không quá cầu kỳ. Bạn có thể lựa chọn thịt thăn để đảm bảo thịt mềm vừa phải và có độ ngọt. Có thể ít hoặc nhiều hơn lượng thịt trên tùy theo nhu cầu. Chuẩn bị thêm một chút salad hoặc măng tây để ăn kèm để bữa ăn thêm phần phong phú và bắt mắt.',
      'Với cách làm bò bít tết tại nhà này bạn sẽ không phải tốn quá nhiều thời gian chuẩn bị. Chỉ cần cẩn thận bày biện sao cho thật đẹp mắt. Một đĩa để bao gồm một miếng thịt, một trứng ốp la, một chút khoai tây. Để cho hương vị đậm đà hơn thì bạn chuẩn bị thêm một phần nước sốt tưới lên trên mặt thịt.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '13',
    name: 'Buldak',
    photoURL: '',
    price: 280000,
    description: [
      'Bít tết sẽ là lựa chọn tuyệt vời cho những bữa tiệc sang chảnh tại nhà với hướng vị thơm ngon lại dễ làm. Dưới đây là cách làm bò bít tết tại nhà đơn giản nhất dành cho bạn nào muốn tự tay chuẩn bị bữa tiệc cho gia đình mình dịp lễ này.',
      'Cách làm bò bít tết tại nhà đơn giản, nguyên liệu cần chuẩn bị cũng không quá cầu kỳ. Bạn có thể lựa chọn thịt thăn để đảm bảo thịt mềm vừa phải và có độ ngọt. Có thể ít hoặc nhiều hơn lượng thịt trên tùy theo nhu cầu. Chuẩn bị thêm một chút salad hoặc măng tây để ăn kèm để bữa ăn thêm phần phong phú và bắt mắt.',
      'Với cách làm bò bít tết tại nhà này bạn sẽ không phải tốn quá nhiều thời gian chuẩn bị. Chỉ cần cẩn thận bày biện sao cho thật đẹp mắt. Một đĩa để bao gồm một miếng thịt, một trứng ốp la, một chút khoai tây. Để cho hương vị đậm đà hơn thì bạn chuẩn bị thêm một phần nước sốt tưới lên trên mặt thịt.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '14',
    name: 'Mexican black bean salad',
    photoURL: '',
    price: 140000,
    description: [
      'Salad là hỗn hợp gồm có rau củ và nước sốt, có thể được ướp lạnh trước khi dùng hoặc ăn trực tiếp (ở nhiệt độ phòng).',
      'Salad là tên gọi tiếng Anh và được xuất hiện lần đầu vào thế kỷ 14 với cách viết là salad hoặc sallet. Ngoài ra, nguồn gốc của tên gọi salad có thể được biến tấu từ cách viết của tiếng Pháp như salade, tiếng Latinh cổ đại là herba Salata và tiếng Latin là salata.',
      'Món salad được xuất hiện từ lâu, dưới nhiều hình thức chế biến khác nhau. Chẳng hạn, người La Mã, người Hy Lạp cổ đại và người Ba Tư đã trộn hỗn hợp rau củ với một loại nước sốt để ăn. Những món ăn rau trộn như vậy đã trở nên phổ biến ở châu Âu sau cuộc xâm lấn của đế chế La Mã và Hy Lạp.',
      'Hầu như nguyên liệu làm nên món salad chủ yếu là các loại rau củ với nước sốt, và tùy theo mục đích sử dụng mới dùng thêm thực phẩm chứa hàm lượng chất đạm như thịt, trứng,… hoặc dùng nước sốt ngọt như kem để thay cho nước sốt giấm quen thuộc.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '15',
    name: 'Green Chicken Salad',
    photoURL: '',
    price: 125000,
    description: [
      'Salad là hỗn hợp gồm có rau củ và nước sốt, có thể được ướp lạnh trước khi dùng hoặc ăn trực tiếp (ở nhiệt độ phòng).',
      'Salad là tên gọi tiếng Anh và được xuất hiện lần đầu vào thế kỷ 14 với cách viết là salad hoặc sallet. Ngoài ra, nguồn gốc của tên gọi salad có thể được biến tấu từ cách viết của tiếng Pháp như salade, tiếng Latinh cổ đại là herba Salata và tiếng Latin là salata.',
      'Món salad được xuất hiện từ lâu, dưới nhiều hình thức chế biến khác nhau. Chẳng hạn, người La Mã, người Hy Lạp cổ đại và người Ba Tư đã trộn hỗn hợp rau củ với một loại nước sốt để ăn. Những món ăn rau trộn như vậy đã trở nên phổ biến ở châu Âu sau cuộc xâm lấn của đế chế La Mã và Hy Lạp.',
      'Hầu như nguyên liệu làm nên món salad chủ yếu là các loại rau củ với nước sốt, và tùy theo mục đích sử dụng mới dùng thêm thực phẩm chứa hàm lượng chất đạm như thịt, trứng,… hoặc dùng nước sốt ngọt như kem để thay cho nước sốt giấm quen thuộc.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '16',
    name: 'Garlic Prime Rib',
    photoURL: '',
    price: 320000,
    description: [
      'Salad là hỗn hợp gồm có rau củ và nước sốt, có thể được ướp lạnh trước khi dùng hoặc ăn trực tiếp (ở nhiệt độ phòng).',
      'Salad là tên gọi tiếng Anh và được xuất hiện lần đầu vào thế kỷ 14 với cách viết là salad hoặc sallet. Ngoài ra, nguồn gốc của tên gọi salad có thể được biến tấu từ cách viết của tiếng Pháp như salade, tiếng Latinh cổ đại là herba Salata và tiếng Latin là salata.',
      'Món salad được xuất hiện từ lâu, dưới nhiều hình thức chế biến khác nhau. Chẳng hạn, người La Mã, người Hy Lạp cổ đại và người Ba Tư đã trộn hỗn hợp rau củ với một loại nước sốt để ăn. Những món ăn rau trộn như vậy đã trở nên phổ biến ở châu Âu sau cuộc xâm lấn của đế chế La Mã và Hy Lạp.',
      'Hầu như nguyên liệu làm nên món salad chủ yếu là các loại rau củ với nước sốt, và tùy theo mục đích sử dụng mới dùng thêm thực phẩm chứa hàm lượng chất đạm như thịt, trứng,… hoặc dùng nước sốt ngọt như kem để thay cho nước sốt giấm quen thuộc.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '17',
    name: 'Beef Steaks',
    photoURL: '',
    price: 280000,
    description: [
      'Với miếng thịt bò tự nhiên có độ tươi ngon mang đẳng cấp Châu Âu và một không gian ấm cúng cùng gia đình, lãng mạng hợp khẩu vị. Hãy liên hệ với chúng tôi một cuộc điện thoại hoặc một tin nhắn thì bạn sẽ được chúng tôi tư vấn tất cả sản phẩm tốt nhất tại cửa hàng để chế biến món Steak gia gia đình thân yêu mà khỏi phải ra các nhà hàng đắt đỏ.',
      'Đặc trưng là miếng thịt bò được cắt lát mỏng và phẳng, thường được cắt vuông góc với các sợi cơ và  sau đó được nướng, chiên hơi tái.',
      'Gia vị thuần tự nhiên (organic) chỉ dùng muối, tiêu & dầu olive (bơ pháp cũng dc) lá hương thảo.',
      'Điểm đặc biệt để quyết định món Steak ngon hay không ngon và do ở miếng thịt có đủ tiêu chuẩn để chế biến hay không nhé cả nhà .Do lẻ đó nên độ mềm miếng Steak là “linh hồn” quyết định 90% độ ngon của món ăn này, việc bạn cần làm là tìm cho mình những miếng thịt có độ mềm phù hợp với món ăn nhưng cũng phải hợp với túi tiền nhé.',
    ],
    category: 'Món phụ',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '18',
    name: 'Gà tẩm bột phô mai',
    photoURL: '',
    price: 59000,
    description: [
      'Gà rán miền Nam Hoa Kỳ, hay còn gọi là gà rán, là một món ăn xuất xứ từ miền Nam Hoa Kỳ; nguyên liệu chính là những miếng thịt gà đã được lăn bột rồi chiên trên chảo, chiên ngập dầu, chiên áp suất hoặc chiên không dầu. Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. Nguyên liệu được sử dụng phổ biến nhất là gà thịt.',
      'Những tính từ dùng để mô tả món gà rán là "giòn rụm", "mọng", "giòn tan"; hoặc cũng có thể là "cay" hoặc "mặn". Tùy cách chế biến mà cũng có thể cho một số loại ớt như bột paprika, hoặc tương ớt lên gà rán để tạo vị cay, kiểu này đặc biệt phổ biến ở các chuỗi nhà hàng thức ăn nhanh như KFC. Theo truyền thống, gà rán sẽ được ăn kèm với khoai tây nghiền, nước thịt, mì ống macaroni và pho mát, xà lách coleslaw, ngô cũng như bánh mì biscuits.',
      'Thông thường, người ta không rán nguyên con gà mà chặt thành các bộ phận riêng. Phần thịt trắng là ức và cánh ở mặt trước của gà, trong khi phần thịt sẫm màu là đùi, chân hoặc "đùi tỏi" ở mặt sau con gà. Ức thường được chia thành hai mảnh và không dùng đến phần lưng. Miếng gà, tức những mảnh ức gà không xương được cắt thành miếng dài, cũng phổ biến.',
    ],
    category: 'Gà rán',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '19',
    name: 'Gà tẩm bột',
    photoURL: '',
    price: 59000,
    description: [
      'Gà rán miền Nam Hoa Kỳ, hay còn gọi là gà rán, là một món ăn xuất xứ từ miền Nam Hoa Kỳ; nguyên liệu chính là những miếng thịt gà đã được lăn bột rồi chiên trên chảo, chiên ngập dầu, chiên áp suất hoặc chiên không dầu. Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. Nguyên liệu được sử dụng phổ biến nhất là gà thịt.',
      'Những tính từ dùng để mô tả món gà rán là "giòn rụm", "mọng", "giòn tan"; hoặc cũng có thể là "cay" hoặc "mặn". Tùy cách chế biến mà cũng có thể cho một số loại ớt như bột paprika, hoặc tương ớt lên gà rán để tạo vị cay, kiểu này đặc biệt phổ biến ở các chuỗi nhà hàng thức ăn nhanh như KFC. Theo truyền thống, gà rán sẽ được ăn kèm với khoai tây nghiền, nước thịt, mì ống macaroni và pho mát, xà lách coleslaw, ngô cũng như bánh mì biscuits.',
      'Thông thường, người ta không rán nguyên con gà mà chặt thành các bộ phận riêng. Phần thịt trắng là ức và cánh ở mặt trước của gà, trong khi phần thịt sẫm màu là đùi, chân hoặc "đùi tỏi" ở mặt sau con gà. Ức thường được chia thành hai mảnh và không dùng đến phần lưng. Miếng gà, tức những mảnh ức gà không xương được cắt thành miếng dài, cũng phổ biến.',
    ],
    category: 'Gà rán',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '20',
    name: 'Bốn miếng cánh gà',
    photoURL: '',
    price: 59000,
    description: [
      'Gà rán miền Nam Hoa Kỳ, hay còn gọi là gà rán, là một món ăn xuất xứ từ miền Nam Hoa Kỳ; nguyên liệu chính là những miếng thịt gà đã được lăn bột rồi chiên trên chảo, chiên ngập dầu, chiên áp suất hoặc chiên không dầu. Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. Nguyên liệu được sử dụng phổ biến nhất là gà thịt.',
      'Những tính từ dùng để mô tả món gà rán là "giòn rụm", "mọng", "giòn tan"; hoặc cũng có thể là "cay" hoặc "mặn". Tùy cách chế biến mà cũng có thể cho một số loại ớt như bột paprika, hoặc tương ớt lên gà rán để tạo vị cay, kiểu này đặc biệt phổ biến ở các chuỗi nhà hàng thức ăn nhanh như KFC. Theo truyền thống, gà rán sẽ được ăn kèm với khoai tây nghiền, nước thịt, mì ống macaroni và pho mát, xà lách coleslaw, ngô cũng như bánh mì biscuits.',
      'Thông thường, người ta không rán nguyên con gà mà chặt thành các bộ phận riêng. Phần thịt trắng là ức và cánh ở mặt trước của gà, trong khi phần thịt sẫm màu là đùi, chân hoặc "đùi tỏi" ở mặt sau con gà. Ức thường được chia thành hai mảnh và không dùng đến phần lưng. Miếng gà, tức những mảnh ức gà không xương được cắt thành miếng dài, cũng phổ biến.',
    ],
    category: 'Gà rán',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '21',
    name: 'Gà chiên siêu cay',
    photoURL: '',
    price: 69000,
    description: [
      'Gà rán miền Nam Hoa Kỳ, hay còn gọi là gà rán, là một món ăn xuất xứ từ miền Nam Hoa Kỳ; nguyên liệu chính là những miếng thịt gà đã được lăn bột rồi chiên trên chảo, chiên ngập dầu, chiên áp suất hoặc chiên không dầu. Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. Nguyên liệu được sử dụng phổ biến nhất là gà thịt.',
      'Những tính từ dùng để mô tả món gà rán là "giòn rụm", "mọng", "giòn tan"; hoặc cũng có thể là "cay" hoặc "mặn". Tùy cách chế biến mà cũng có thể cho một số loại ớt như bột paprika, hoặc tương ớt lên gà rán để tạo vị cay, kiểu này đặc biệt phổ biến ở các chuỗi nhà hàng thức ăn nhanh như KFC. Theo truyền thống, gà rán sẽ được ăn kèm với khoai tây nghiền, nước thịt, mì ống macaroni và pho mát, xà lách coleslaw, ngô cũng như bánh mì biscuits.',
      'Thông thường, người ta không rán nguyên con gà mà chặt thành các bộ phận riêng. Phần thịt trắng là ức và cánh ở mặt trước của gà, trong khi phần thịt sẫm màu là đùi, chân hoặc "đùi tỏi" ở mặt sau con gà. Ức thường được chia thành hai mảnh và không dùng đến phần lưng. Miếng gà, tức những mảnh ức gà không xương được cắt thành miếng dài, cũng phổ biến.',
    ],
    category: 'Gà rán',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '22',
    name: 'Ức gà chiên siêu cay',
    photoURL: '',
    price: 69000,
    description: [
      'Gà rán miền Nam Hoa Kỳ, hay còn gọi là gà rán, là một món ăn xuất xứ từ miền Nam Hoa Kỳ; nguyên liệu chính là những miếng thịt gà đã được lăn bột rồi chiên trên chảo, chiên ngập dầu, chiên áp suất hoặc chiên không dầu. Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. Nguyên liệu được sử dụng phổ biến nhất là gà thịt.',
      'Những tính từ dùng để mô tả món gà rán là "giòn rụm", "mọng", "giòn tan"; hoặc cũng có thể là "cay" hoặc "mặn". Tùy cách chế biến mà cũng có thể cho một số loại ớt như bột paprika, hoặc tương ớt lên gà rán để tạo vị cay, kiểu này đặc biệt phổ biến ở các chuỗi nhà hàng thức ăn nhanh như KFC. Theo truyền thống, gà rán sẽ được ăn kèm với khoai tây nghiền, nước thịt, mì ống macaroni và pho mát, xà lách coleslaw, ngô cũng như bánh mì biscuits.',
      'Thông thường, người ta không rán nguyên con gà mà chặt thành các bộ phận riêng. Phần thịt trắng là ức và cánh ở mặt trước của gà, trong khi phần thịt sẫm màu là đùi, chân hoặc "đùi tỏi" ở mặt sau con gà. Ức thường được chia thành hai mảnh và không dùng đến phần lưng. Miếng gà, tức những mảnh ức gà không xương được cắt thành miếng dài, cũng phổ biến.',
    ],
    category: 'Gà rán',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '23',
    name: 'Combo burger và khoai chiên',
    photoURL: '',
    price: 199000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Combo',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '24',
    name: 'Combo burger 2 tầng, khoai chiên và nước sốt đặc biệt',
    photoURL: '',
    price: 219000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Combo',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '25',
    name: 'Combo 3 burger kinh điển',
    photoURL: '',
    price: 259000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Combo',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    productId: '26',
    name: 'Suất siêu đầy đủ',
    photoURL: '',
    price: 359000,
    description: [
      'Luôn được ưu chuộng dù bất kì ở chi nhánh hay cửa hàng nào đó là món Whopper trứ danh với các nguyên liệu hấp dẫn không thể chối từ như thịt nướng xém lửa thơm ngon mềm mại nhưng không kém phần bổ dưỡng, những lát cà chua và rau tươi ngon, và điều quan trọng làm nên món bánh hấp dẫn này đó chính là nước sốt mayonnaise và mustard hấp dẫn, không ở đâu có được.',
      'Ngoài món Whopper trứ danh đó ra thì bạn không thể bỏ lỡ Burger gà với miếng ức gà được chiên vàng giòn rụm ăn kèm với rau xà lách và cà chua tươi ngon, ăn rất quyện vị với hai lát bánh mềm mỏng, một món ăn nhanh tuyệt vời, vừa đáp ứng được hai tiêu chí vừa ngon vừa rẻ.',
      'Nếu bạn bỏ lỡ món bánh Burger Bò hấp dẫn tại Quick Food thì quả thật đó là một sai sót khá lớn. Không gì tuyệt vời hơn với những lát thịt nguội bacon giòn tan hòa quyện với lát phô mai Cheddar và thịt bò nướng lửa.',
      'Ngoài những món bánh burger đã làm nên tên tuổi của Quick Food đó ra thì bạn có thể thưởng thức các món ăn kèm như khoai tây chiên giòn, mực chiên vòng, gà miếng,..',
    ],
    category: 'Combo',
    avgRating: 0,
    quantityRemaining: 10,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
];

export const productReviews = [
  {
    userId: '1KaZONkPVabTAXTZsUUMVakjHRXe',
    productId: '30ed0930-7e94-4c61-a40d-883703cd42b9',
    contents: ['món ăn tuyệt vời', 'phù hợp với giá tiền'],
    rating: 0,
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
];

export const blogs = [
  {
    blogId: '1',
    title:
      'Sức lôi cuốn không thể chối từ của burger tôm hai tầng cho người thưởng thức',
    contents: [
      'Một chiếc burger tôm truyền thống đã làm những người thưởng thức nó nao lòng. Vậy còn gì tuyệt hơn khi có sự kết hợp hai tầng tôm trong cùng một chiếc bánh. Khám phá ngay chiếc burger tôm hai tầng qua bài viết sau để giúp bạn có thêm lựa chọn thú vị trong mỗi bữa ăn của mình nào.',
      'Burger tôm hai tầng có nguyên liệu chính là những con tôm nõn, thêm vào đó là những lá rau sống tươi mát, vỏ bánh mì mềm, thơm, lớp sốt sánh quyện. Bạn sẽ không khỏi bất ngờ ngay từ khi thưởng thức miếng bánh đầu tiên đâu đấy. Lần lượt từ lớp bánh mịn bao bọc bên ngoài, cho đến những con tôm giòn rụm ở lớp nhân và hương thơm, vị bùi của lớp rau xà lách được sắp xếp đan xen.',
      'Sự kết hợp ăn ý, hòa nhập, làm nên món bánh burger bổ ích, hấp dẫn. Người dùng sẽ không phải lo sự ngấy mỡ như một số món ăn khác, mà đối với chiếc burger này thì những lớp tôm thật sự rất giòn bởi được chiên theo cách thức rất riêng, đặc biệt.',
    ],
    category: 'Burger',
    images: [
      'https://chianui.vn/wp-content/uploads/2019/08/hamburger-ga-2-tang-compressed.jpg',
      'https://chianui.vn/wp-content/uploads/2019/03/burger-tom-hai-tang-.png',
    ],
    timeGroup: '2021-07',
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    blogId: '2',
    title: 'BÁNH BURGER BUN (BÁNH MÌ BUGER) HẤP DẪN',
    contents: [
      'Ai cũng có suy nghĩ là Hamburger xuất phát từ Mỹ – nơi hàng tỉ chiếc bánh này được tiêu thụ mỗi năm. Nhưng sự thật thì chiếc bánh Hamburger đầu tiên được sáng tạo ra ở thành phố Hamburg, nước Đức. Lấy cảm hứng từ món bánh này mà ít lâu sau món bánh sandwich được sáng tạo ra. Đến năm 1916 thì một đầu bếp người Mỹ tên Walter Anderson đã thêm nhân thịt bò vào Hamburger làm ra loại bánh mì đặc biệt liên tục phát triển và tung hoành ở Mỹ cũng như nhiều quốc gia trên thế giới.',
      'Ngày nay, bánh Hamburger xuất hiện ở nhiều quốc gia trên thế giới.Vỏ bánh mềm ngọt, kết hợp cùng hương vị đa dạng bên trong nhân bánh với xà lách thật giòn, phô mai thật béo, thịt thơm đậm đà và cà chua mọng nước – ai có thể chối từ món bánh ngon như vậy? Công thức làm Hamburger với nhân thịt bò bằm và bánh mì phủ mè được chia sẻ dưới đây chắc chắn sẽ làm bạn ngạc nhiên.',
      'Cho bột mì, muối, men khô và đường vào âu, trộn đều. Sữa tươi đem đun nhẹ rồi thêm 2 quả trứng đã đánh tan vào sữa, khuấy đều. Tiếp theo, từ từ đổ hỗn hợp sữa vào âu bột, trộn lên để các nguyên liệu hòa quyện vào nhau. Sau đó thêm bơ mềm vào trộn cùng. Đặt bột lên mặt phẳng, nhào bằng tay khoảng 15 phút. Nhào xong thì gói bột lại bằng màng bọc thực phẩm, ủ bột ở nhiệt độ từ 30 – 35 độ C.',
      'Bột sau khi ủ xong thì chia thành nhiều phần nhỏ có trọng lượng bằng nhau, nhào từng viên bột và vê tròn, đặt lên khay. Ủ bột lần 2 thêm 10 phút nữa. Lưu ý: Khoảng cách giữa các viên bột khoảng 5cm để khi nướng chín bánh không bị dính vào nhau. Phết trứng và rắc vừng lên mặt bột. Làm nóng lò nướng ở 180 độ C trước 10 phút rồi cho khay bánh vào lò, phun nước lên mặt, nướng 15 phút. Lần lượt cho các nguyên liệu làm nhân bánh vào âu (trừ bread crumb), trộn đều. Thêm bread crumb vào một cách từ từ để quan sát độ kết dính. Khi thấy nhân đã được thì đổ ra khay, dàn đều sao cho nhân có độ dày từ 1 – 1.5cm, đặt vào ngăn đông 24 giờ. Lấy nhân ra, cho vào lò vi sóng để rã đông. Tiếp theo, chia nhân nhỏ ra, nặn hành hình tròn rồi chiên vàng đều 2 mặt. Cắt đôi vỏ bánh theo chiều ngang, cho nhân thịt vào chính giữa, thêm xà lách, cà chua, phô mai… tùy theo khẩu vị của bạn và thưởng thức.',
    ],
    category: 'Burger',
    images: [
      'https://cdn.daylambanh.edu.vn/wp-content/uploads/2015/10/hamburger-bun.jpg',
    ],
    timeGroup: '2021-05',
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
  {
    blogId: '3',
    title: 'SALAD TRÁI CÂY',
    contents: [
      'Với nguyên liệu chính là nhiều loại trái cây tươi ngon cùng cách chế biến đơn giản, món salad trái cây là một sự lựa chọn tuyệt vời cho những buổi tối cuối tuần quây quần bên gia đình, có tác dụng giải nhiệt rất tốt. Nguyên liệu: dưa leo 1/2 trái, dưa lưới nhỏ 1 miếng, dâu tây 5 trái, lê 1/2 trái, táo đỏ 1/2 trái, nho khô 10g, xà lách 3 lá, sữa đặc có đường, sữa chua có đường, muối, tiêu, đường, xốt mayonnaise.',
      'Dâu tây cắt đôi, ướp với 1m đường, để 10 phút. Nho khô ngâm nước 10 phút, để ráo. Dưa leo để vỏ, bỏ ruột, cắt miếng vuông 1cm. Xà lách cắt sợi 1cm. Lê, dưa lưới gọt vỏ, cắt miếng vuông 1cm. Táo để nguyên vỏ, cắt miếng vuông 1cm, ngâm vào nước muối pha loãng, vớt ra để ráo. Táo cắt xong ngâm vào nước muối pha loãng để không bị đen.',
      'Pha xốt: Trộn đều 3M Xốt Mayonnaise “Aji-mayo” với 1M sữa đặc có đường và 1M sữa chua. Cho các loại trái cây vào tô, trộn đều với hỗn hợp xốt vừa trộn. Xếp xà lách ra dĩa, cho trái cây trộn lên trên.',
    ],
    category: 'Món phụ',
    images: [
      'https://cdn.daylambanh.edu.vn/wp-content/uploads/2015/10/hamburger-bun.jpg',
    ],
    timeGroup: '2021-05',
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
];

export const blogReviews = [
  {
    userId: '1KaZONkPVabTAXTZsUUMVakjHRXe',
    blogId: '3b772743-0c32-454b-a103-420f9e310d7a',
    comments: [
      'Món ăn tuyệt vời',
      'Vậy! Làm sao để bạn có thể đặt mua những chiếc burger tôm cho mình và gia đình một cách nhanh chóng nhất, với mức giá phù hợp nhất?',
    ],
    removed: false,
    createdAt: null,
    updatedAt: null,
  },
];

export const carts = [
  {
    userId: '1KaZONkPVabTAXTZsUUMVakjHRXe',
    productId: '30ed0930-7e94-4c61-a40d-883703cd42b9',
    quantity: 2,
    paymentStatus: false,
    createdAt: null,
    updatedAt: null,
  },
];
